### ISSUE TITLE
Specify EXTERNAL_NET vs HOME_NET

### ISSUE THREAD

**Issue by arnydo** [activecm/rita#211]
Is there an option to specify EXTERNAL_NET(s) vs HOME_NET(s) similar to Snort/Surricata?
Most of the analysis is reporting on internal networking rather than comms going to external sites.

Thank you for this excellent resource!!!!!

**Comment by ethack** [comment]
@arnydo The only analog I'm aware of is the `networks.cfg` configuration in Bro.  I'd double-check that this matches your internal networks.  This file is located in `/opt/bro/etc/networks.cfg` by default but its default values are usually already set to the normal internal network IP ranges.  I don't think RITA will report on external->external, but I think it does report on internal->internal just like you are seeing.

https://github.com/bro/broctl/blob/master/etc/networks.cfg
https://www.bro.org/sphinx/components/broctl/README.html#configuration

If you can filter out internal->internal traffic before it reaches Bro you could accomplish this and possibly see a performance improvement because Bro/RITA won't have to process that extra traffic.

**Comment by arnydo** [comment]
Thank you @ethack! Good to know it relies on Bro for this type of config.

I made the updates to Bro but when I now go in to re-import and/or analyze nothing happens.

I have tried reinstalling, clearing the DB, checking configs, etc...

Any ideas?

![image](https://user-images.githubusercontent.com/11653079/40239669-ae01ca26-5a84-11e8-926e-f12fd5322da2.png)

**Comment by ethack** [comment]
@arnydo My apologies for dropping this conversation.  I'm closing this as an old issue, but if you are still having this problem and would like help troubleshooting please let us know.
