### ISSUE TITLE
rita v2.0.0-beta1 bro log parsing error

### ISSUE THREAD

**Issue by idbran** [activecm/rita#351]
Just upgraded to rita version v2.0.0-beta1 on a system running bro-2.6.1-1.2.x86_64. Receiving the following error in the warn.log during the data imports:
> msg="An error was encountered while indexing a file" error="Could not map file header to parse type"

Looked at issues #249, #217, and #146 but it doesn't appear to be related to those. I verified that the unzipped bro logs are not in JSON format. Some imports are working, such as the DNS logs and User Agents. But the beacon analysis is not working, I assume because the conn or conn-summary logs are failing.

Here is an example header from a conn log:
`#separator \x09
#set_separator  ,
#empty_field    (empty)
#unset_field    -
#path   conn
#open   2019-01-19-22-00-01
#fields ts      uid     id.orig_h       id.orig_p       id.resp_h       id.resp_p       proto   service duration        orig_bytes      resp_bytes      conn_state      local_orig      local_resp      missed_bytes    history orig_pktsorig_ip_bytes    resp_pkts       resp_ip_bytes   tunnel_parents
#types  time    string  addr    port    addr    port    enum    string  interval        count   count   string  bool    bool    count   string  count   count   count   count   set[string]
`
My configuration is pretty vanilla. Could this be a parser issue or should I go back and look through config files some more? Any help is appreciated, thanks in advance!

**Comment by ethack** [comment]
Hello @idbran 

I suspect that the warning message is a red herring but let's start by trying to rule it out.  Could you look at the `file` portion of that log message as well and confirm that none of those messages are an error in any conn, http, or dns logs?  It is normal for that message to be logged when rita encounters any of Bro's other log files.  For example, the x509 log:
```
time="2019-01-18T13:48:43-06:00" level=warning msg="An error was encountered while indexing a file" error="Could not map file header to parse type" file="activecm/sample-data/bro/empire-http-jitter/x509.02:00:00-03:00:00.log.gz"
```

The most likely culprit for the issue you're seeing is a new addition to the config file in the beta1 release.  You must configure the `InternalSubnets` section in your `/etc/rita/config.yaml` file:
https://github.com/activecm/rita/blob/master/etc/rita.yaml#L85-L93
By default, it is commented out and there is a bug in beta1 that will filter out all traffic if this is not configured.  In the full v2 release this will produce and error on import and not let you continue without configuring it.  Most people can just uncomment the example provided in the config file but we can't just include that by default because there are enough people where that configuration will cause problems.

Additionally, you'll need to make sure that your Bro `networks.cfg` file is correct.  This won't be necessary in the v2 release but for the beta it is.  The path in the default install is `/opt/bro/etc/networks.cfg` but may be different if you installed Bro a different way.  Just make the networks in this file match the ones you put in RITA's config.

**Comment by idbran** [comment]
Confirmed your suspicion on the error log - it was not for conn, http, or dns.

I think that you are correct with the new config file settings. When I compared mine with the repo I was also missing the following sections:

```
ImportBuffer: 30000
UserConfig:
Beacon:
DNS:
UserAgent:
Strobe:
```
I suspect that since I ran the upgrade over the top of the older install it preseved my old config file, which didn't have the new settings. I manually edited it to match the default settings.

I will also validate the networks.cfg for Bro and then re-run the imports and see how it goes.

**Comment by idbran** [comment]
Looks like that fixed the problem. For future upgrades, would it be preferable to remove/rename config files before running the upgrade?

Thanks again for the help.

**Comment by ethack** [comment]
We now include sane default settings for every new config value inside of rita's binary so that older config files will work fine.  InternalSubnets has been the outlier that's caused problems recently, which is why we haven't yet moved out of beta, and we have to special case if that is not configured going forward.  I'd like to have a way to upgrade config files in place in the future but that isn't ready yet.

When you upgrade rita it downloads the newest config file to `/etc/rita/config.yaml.new` but doesn't overwrite your current config.  You can run a `diff` on the two files and also use `rita test-config` to see if there are any new/different config options that you wish to change from the default values.

I'll make sure to get some documentation in surrounding the InternalSubnets and upgrading before the rita v2 full release.
