### ISSUE TITLE
Add support for Debian

### ISSUE THREAD

**Issue by debernal** [activecm/rita#430]
Hi, 

Are there any plans to support Debian operating system?, would be much appreciated, thanks.

**Comment by ethack** [comment]
Hello @debernal.  We don't currently have plans to add official support for Debian.  But since we support Ubuntu, it should be relatively straightforward to get it working.  If you didn't want to debug and modify the automatic install script, you could use the [manual install instructions](https://github.com/activecm/rita/blob/master/docs/Manual%20Installation.md) or [use docker](https://github.com/activecm/rita/blob/master/docs/Docker%20Usage.md).
