### ISSUE TITLE
Strange UserAgent String in RITA Results

### ISSUE THREAD

**Issue by el-jako-86** [activecm/rita#490]
+------------------------------------------------------------------------------+------------+
|                                  USER AGENT                                  | TIMES USED |
+------------------------------------------------------------------------------+------------+
| **b20b44b18b853ef29ab773e921b03422**                                             |         83 |
| Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0 |         40 |
| **839bbe3ed07fed922ded5aaf714d6842**                                             |         18 |
| **d470a3fa301d80227bc5650c75567d25**                                             |         11 |
| **334da95730484a993c6063e36bc90a47**                                             |          5 |
| Wget/1.19.4 (linux-gnu)                                                      |          1 |
+------------------------------------------------------------------------------+------------+

**Comment by el-jako-86** [comment]
When checking the same logs using bro, I get a different output as follows:

zcat http.* | bro-cut user_agent | sort -u

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0
Wget/1.19.4 (linux-gnu)

**Comment by ethack** [comment]
Do you have the [ja3 plugin](https://github.com/salesforce/ja3/tree/master/bro) installed and enabled? Rita's installer will install it automatically. 

Those look like ja3 hashes for TLS/SSL which will go into the same place as user agents. Ja3 hashes are used instead of user agents when the connection is encrypted since we cannot read the user agent string in those connections. If you want to look for those strings they'd be in the ssl.log files.

**Comment by el-jako-86** [comment]
Spot on! - Thanks that was it. Like you said I found the same hash reference in the ssl.log and the heading in the bro logs says **ja3**. 

On a side note... I have just started looking into RITA for a school project I am working on. My goal is to detect the abuse of legitimate web services (Gmail, Twitter, etc.) for command and control communications. Where can I obtain more information on the inner workings of RITA (example: how the K-Means algorithm is being used, what features are evaluated by the algorithm to detect beacon activity, etc.)?

Big ups for the work and dedication put into RITA! It has been of great help to my project.

**Comment by ethack** [comment]
Nice! That's definitely a great topic to pursue. Rita should do a pretty good job detecting that type of thing already. The problem is telling that apart from normal usage. Because most of those services are going to poll beacon-like in the background if a user just leaves a tab open in their browser. So if there are other users of those services Rita isn't going to give much in the way of differentiating malicious or not. 

The longer the beacon stays active will increase the score so if the malware keeps it up all day and the users close their browsers at some point that would be one way. But that could go the other way too as more advanced malware could set working hours and go dormant during the night. Conversely, users could leave their computers on all night as well and have those services be polling in the background the whole time.

We don't use K-Means in Rita. We might have a long time ago, but I think the problem was that it was very slow. We just started adding some documentation around what stats Rita uses which you can find [here](https://github.com/activecm/rita/blob/273-documentation-for-output/docs/Understanding%20RITA%20Measurements.md). The other place you can look is by reading the code [here](https://github.com/activecm/rita/blob/master/pkg/beacon/analyzer.go#L87-L228). The code is pretty straightforward if you're familiar with the statistics it's calculating. There should be enough in the comments to go on to google them but if there is any part you get stuck on, feel free to reach out again.

**Comment by bekirk** [comment]
I have a question on this issue.  I don't have Zeek on the system that rita is installed.  I use corelight so the logs are sent to the rita system every hour.  How do I fix this in this case?  I don't need to see all the JA3's in the user agent field.  Is there was way tell rita that the ja3 will be there?
