### ISSUE TITLE
BL pairs for show-x commands

### ISSUE THREAD

**Issue by bowserkn** [activecm/rita#492]
In the html report there are BL pairs (shows source and destination), is there anyway to show these BL pairs using the show-x commands? It would be really useful to have the pairs in both the html report and the show-x commands.

For example:
In the html report for "BL Source IPs," I see the following headers --> "IP, Connections, Unique Connections, Total Bytes, & Destinations"

But when I type "rita show-bl-source-ips test-dataset -H | less -S" it shows me the following sections --> "IP, Connections, Unique Connections, Total Bytes"

Can I get the show command to show me the destination header as well or no? I didn't specifically see anything in the documentation regarding this, but I may have missed it. 

Thank you!

**Comment by ethack** [comment]
If you run `rita show-bl-source-ips --help` there should be a list of options available.  Try out this one and see if it gives you what you're looking for.
```
rita show-bl-source-ips --connected test-dataset
```

I think it's not the default because it may take longer to run. So if you have a large dataset be prepared to wait longer for it to finish. But on the plus side v3.0.5 introduced the `--limit` flag as well so you can do something like this if you have too many entries.
```
rita show-bl-source-ips --connected --limit 10 test-dataset
```

**Comment by bowserkn** [comment]
Yes that's exactly what I was looking for, thank you ethack!
