### ISSUE TITLE
Update after adding whitelist entry

### ISSUE THREAD

**Issue by bowserkn** [activecm/rita#498]
Can someone please explain what I am doing wrong, I want to whitelist a false positive beacon. 
1) I generate my RITA report.
2) I see a source beacon that is a false positive, and whitelist the source IP in CIDR notation (ex 192.168.1.1/32) under "NeverInclude"
3) The next day I import new logs (I keep 7 days worth at any given time with --rolling --numchunks)
 4) Generate a new report and it still shows the source beacon that I whitelisted as a beacon.

**Comment by ethack** [comment]
The settings under the `Filtering` config section are only applied to new data that gets imported and not existing data.

If I'm understanding your workflow right, you'll have old data still in your rolling database until you import 7 new days' worth to rotate it all out.  You can try importing your new logs into a different database and see if the beacon still shows up there (it shouldn't so let us know otherwise).  And if you don't want to wait for all the old data to get rotated out, you can make a new rolling dataset and import the data you have up to this point and use that going forward.

**Comment by bowserkn** [comment]
Thank you Ethack, you are super helpful as always. I tried importing the new logs into a different database and the beacon no longer showed up, so it does work correctly.
