### ISSUE TITLE
Build System Does Not Accommodate Forked Repositories

### ISSUE THREAD

**Issue by joswr1ght** [activecm/rita#532]
The current build system expects a hard-coded path and GitHub repository name `activecm/rita` in several places. This design discourages community collaboration with pull requests using the GitHub fork/modify/PR process.

Recommend reworking the build process so that the build system gets location information from the file system instead of hard-coded in `Makefile`, `rita.go`. Also recommend instruction update to build from source to help developers use a forked repo of RITA for local development.

**Comment by ethack** [comment]
@joswr1ght First of all, thank you for all the changes you contributed recently! I'm curious if your thoughts on this issue have changed after you've made these contributions?

You may be familiar with Go development already, but if not, Go expects packages to be imported based on their path within `$GOPATH/src`. I believe this path can be arbitrary, but all of Go's tooling expects these paths to align with a public git repository. You'll see that nearly every Go file in RITA will import packages from `github.com/activecm/rita/*`. We can tell you from experience this makes renaming an organization or a repo a pain. You'd think that find and replace would catch everything but there's always something that's missed.

I checked the `Makefile` and `rita.go` and any instance of `activecm/rita` is either caused by the aforementioned Go package conventions or the location of our current docker repository. But in both cases, I don't think they should prevent community collaboration. If I'm missing something else let me know. 

Otherwise, I do appreciate your input and one of your changes to the contribution guide made me realize that our documentation there was outdated and could probably be streamlined a bit. I've made updates to the docs and would value your input as to whether this addresses any of the issues you ran into with the contribution workflow. https://github.com/activecm/rita/pull/537

**Comment by joswr1ght** [comment]
I’m new to Go development, and it strikes me as counter to the common GitHub fork and PR process, but after seeing the explanation about changing the remote URL it’s just as easy as non-Go dev. Thank you for the insight and feedback!
