### ISSUE TITLE
Zeek Repository URL Fix

### ISSUE THREAD

**Issue by 0x6d6f7468** [activecm/rita#548]
The OpenSUSE repository for Zeek has moved from the old URL (https://download.opensuse.org/repositories/network:/bro/) to a new URL (https://download.opensuse.org/repositories/security:/zeek/).

All references to OpenSUSE's repository in the installer need to be updated to the new location.

**Comment by bkonsela** [comment]
More information, I didn't want to clutter the issue body too much:

This issue is twofold: We cannot currently install Zeek on Ubuntu, and there is currently no directory in the repository for Ubuntu 16.04, so we can't currently install Zeek on Ubuntu 16.04.

I will go into the installer and change repo URLs to the new locations. As there is currently no 16.04 URL available, I will switch the URL anyway to hopefully preempt its eventual existence. I may end up adding a warning to the script, but it sounds like we're not willing to stop supporting Ubuntu 16.04 because of this issue quite yet.

**Comment by bkonsela** [comment]
This is going to cause headaches, as all references to `bro`-esque binaries will need to be updated to a corresponding `zeek`-esque. After this release, I'll compile a list of all `bro` references across RITA and AI-Hunter in preparation for an inevitable branding shift from `bro` to `zeek`.

**Comment by Zalgo2462** [comment]
Closed by https://github.com/activecm/rita/pull/569
