### ISSUE TITLE
Getting error when trying to run ./installer.sh

### ISSUE THREAD

**Issue by Loruss** [activecm/rita#601]
Hello,
I am getting following error when trying to run ./installer.sh command, "./install.sh: 8: ./install.sh: Syntax error: newline unexpected" 
My Operating system is Ubuntu 18.04.

**Comment by ethack** [comment]
Can you run `head installer.sh` and provide the output here?

Are you invoking the install script as a normal user with `sudo` or some other way? e.g. `sudo ./installer.sh`

**Comment by Loruss** [comment]
Here is the output of head command 
![image](https://user-images.githubusercontent.com/56776342/102941279-2a7baa80-4467-11eb-96c9-d8fd530599b2.png) 
Yes, I invoke the install script as a normal user with sudo. 

P.S. On the screenshot, it shows "./install.sh: 2: ./install.sh: Syntax error: newline unexpected" instead of "./install.sh: 8: ./install.sh..." because I deleted some empty lines in the script, so "head" command would output more lines.

**Comment by ethack** [comment]
Thanks! It looks like the install file you downloaded was the HTML page instead of the shell script.

Here is a direct link to download the install script.
https://github.com/activecm/rita/releases/download/v4.0.0/install.sh

In the future you can find the latest install script on the [releases](https://github.com/activecm/rita/releases) page:
![image](https://user-images.githubusercontent.com/1696711/102941820-425c2a00-4479-11eb-96b1-e08976a381f1.png)

**Comment by Loruss** [comment]
Thank you so much! Everything installed perfectly, after I ran the actual script instead of HTML page :-)
