### ISSUE TITLE
System Requirements : What is the Operating System requirement / preferred platform?

### ISSUE THREAD

**Issue by s-worden** [activecm/rita#659]
Per the main site, supposed to ask questions here. If that is incorrect just let me know how and I will do it appropriately.

The System Requirements page (https://github.com/activecm/rita/blob/master/docs/System%20Requirements.md) states that the preferred operating system is 64-bit Ubuntu 16.04 LTS. As that is end of life is there a different system requirement or preferred operating system assuming not using the Docker version? More directly, which version of Ubuntu should I upgrade to 18.04 or 20.04?

**Comment by ethack** [comment]
I don't think Ubuntu 20.04 is _officially_ supported yet. But it's super close. It might even be that the docs just haven't been updated yet.

In short, if you want tested and no-fuss go with Ubuntu 18.04.
If you want future proofing and don't mind the risk of some minor troubleshooting or extra commands go with 20.04.

Your other options are doing a [manual install](https://github.com/activecm/rita/blob/master/docs/Manual%20Installation.md) on 20.04 (which [others](https://github.com/activecm/rita/issues/587) have had success with) and [docker](https://github.com/activecm/rita/blob/master/docs/Docker%20Usage.md) is an option as well.

**Comment by Zalgo2462** [comment]
20.04 is not supported. Unfortunately, Ubuntu 20.04 does not support MongoDB 4.2 since the earliest version supported by Ubuntu 20.04 is 4.4. So, we will need to introduce a few changes to RITA before officially supporting Ubuntu 20.04. In the meantime, I'd recommend upgrading to 18.04.

However, if you absolutely need 20.04 support, you can install RITA with `--disable-mongo`, install MongoDB 4.2 using Docker `sudo docker run -d --name MongoDB mongo:4.2`, and edit `/etc/rita/config.yaml`'s MongoDB connection string to point to the IP of the container given by `sudo docker inspect MongoDB`.

**Comment by ethack** [comment]
@Zalgo2462 thanks for the correction!
