### ISSUE TITLE
Versioning issues during upgrade

### ISSUE THREAD

**Issue by cbrenton-acm** [activecm/rita#723]
Currently running RITA version 4.3.1. While running RITA I got the banner:
Theres a new Minor version of RITA 4.5.0 available at:
https://github.com/activecm/rita/releases

Navigating to the above page, it looks like 4.5.0 is actually just a pre-release with 4.4.0 being the current production version. I then downloaded install.sh from the page and ran it. When prompted whether I wanted to re-install RITA I answered "yes". This appears to re-install 4.3.1 rather than providing an option to upgrade to 4.4.0.

**Comment by Zalgo2462** [comment]
- It appears there is a bug in the 4.4.0 release where the installation script was not updated to point to the 4.4.0 release.
  - https://github.com/activecm/rita/commits/master/install.sh shows the referenced version went from 4.3.1 to 4.5.0 in the git history
  - I have amended the install script in the 4.4.0 release to point to 4.4.0. 
    - I have tested this change on Ubuntu 18.04 to ensure version 4.4.0 is correctly installed.
  
- It appears that we missed converting the 4.5.0 pre-release into a full release. 
  - This is the version we currently include with AC-Hunter. 
  - I have tested the associated installation script successfully installs version 4.5.0
  - I have converted this into a full release.

I have updated our runbook for releasing new versions of RITA and AC-Hunter in order to help ensure these mistakes do not happen in the future.
