### ISSUE TITLE
Rita Install Script Fail

### ISSUE THREAD

**Issue by vegasjoe** [activecm/rita#821]
May I get help with this Error?

[-] Installing Zeek IDS... SUCCESS

[!] Enabling Zeek on startup.
[!] Enabling Zeek on startup process completed.
[!] Starting Zeek.
checking configurations ...
manager scripts failed.
fatal error in /opt/zeek/share/zeek/site/local.zeek, line 130: can't find policy/protocols/ssl/extract-certs-pem

proxy-1 scripts failed.
fatal error in /opt/zeek/share/zeek/site/local.zeek, line 130: can't find policy/protocols/ssl/extract-certs-pem

worker-1-1 scripts failed.
fatal error in /opt/zeek/share/zeek/site/local.zeek, line 130: can't find policy/protocols/ssl/extract-certs-pem

 lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

**Comment by Zalgo2462** [comment]
Hello, we recently discovered this error and we have developed a fix for it. 
Unfortunately, we have not published it as a release just yet. 

Please download the installation script from the master branch rather than from the latest release until v4.8.1 is out.

Here is a link to the fixed installation script currently in the master branch: 
<a href="https://raw.githubusercontent.com/activecm/rita/c45ad63ea8aac7a2f8950decd4c0b2a7aba037e8/install.sh" download>https://raw.githubusercontent.com/activecm/rita/c45ad63ea8aac7a2f8950decd4c0b2a7aba037e8/install.sh</a>

Sorry for the inconvenience.

**Comment by Zalgo2462** [comment]
Fixed in https://github.com/activecm/rita/releases/tag/v4.8.1
